outfile:main.o RFID.o add.o show.o modify.o delete.o save.o
	cc main.c RFID.c add.c show.c modify.c delete.c save.c -o outfile

main.o : main.c
	cc -c main.c
RFID.o : RFID.c
	cc -c RFID.c
add.o : add.c
	cc -c add.c
show.o : show.c
	cc -c show.c
modify.o : modify.c
	cc -c modify.c
delete.o : delete.c
	cc -c delete.c
save.o : save.c
	cc -c save.c
